GET http://localhost:3333/videos

###

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "CRUD NodeJS",
    "description": "CRUD NodeJS - Video 02",
    "duration": 180
}

###

PUT http://localhost:3333/videos/ba3ea851-6ed9-4a6e-953c-23417f9143b6
Content-Type: application/json

{
    "title": "CRUD NodeJS",
    "description": "CRUD NodeJS - Video 02 v2",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/ba3ea851-6ed9-4a6e-953c-23417f9143b6
